name: Semgrep

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Install semgrep
        run: pip install semgrep
      - name: Scan
        run: semgrep --config p/default --error .
