name: Semgrep

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Install semgrep
        run: pip install semgrep
      - name: Scan
        run: semgrep --config p/default --error .
